### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by allaire** [sinfomicien/mysql2_chef_gem#13]
Getting the following warning, any ideas?

```
 mysql2_chef_gem[default] action install

 ================================================================================
 Error executing action `install` on resource 'mysql2_chef_gem[default]'
 ================================================================================

 TypeError
 ---------
 no implicit conversion of nil into String

 Cookbook Trace:
 ---------------
 /var/chef/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:17:in `block (2 levels) in <class:Mysql>'
 /var/chef/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:16:in `block in <class:Mysql>'
 /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

 Resource Declaration:
 ---------------------
 # In /var/chef/cache/cookbooks/myorg-mysql/recipes/default.rb

   9: mysql2_chef_gem "default" do
  10:   action :install
  11: end
  12:

 Compiled Resource:
 ------------------
 # Declared in /var/chef/cache/cookbooks/myorg-mysql/recipes/default.rb:9:in `from_file'

 mysql2_chef_gem("default") do
   action [:install]
   retries 0
   retry_delay 2
   default_guard_interpreter :default
   declared_type :mysql2_chef_gem
   cookbook_name "myorg-mysql"
   recipe_name "default"
 end

 Platform:
 ---------
 x86_64-linux
```

**Comment by nickma** [comment]
Same issue here

**Comment by heaven** [comment]
Also having the same problem with rvm. As I understand the problem my chef is using system ruby 1.9 while when I do require 'mysql2' from a recipe it is trying to load from ruby 3.3.
