### ISSUE TITLE
Unable to install mysql-client on ubuntu14.04

### ISSUE THREAD

**Issue by snehitgajjar** [sinfomicien/mysql2_chef_gem#23]
**Error Log**

Chef-client : Chef: 12.13.37

OS : ubuntu 14.04

mysql-client version : 5.5

```
Resource Declaration:
        ---------------------
        # In /tmp/kitchen/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb

         18:       package package_name do
         19:         version package_version if package_version
         20:         options package_options if package_options
         21:         action :install
         22:       end
         23:     end

        Compiled Resource:
        ------------------
        # Declared in /tmp/kitchen/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb:18:in `block in <class:MysqlClientInstallationPackage>'

        apt_package("mysql-client-5.5") do
          package_name "mysql-client-5.5"
          action [:install]
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          declared_type :package
          cookbook_name "install_mysql"
          version "5.5.50-0ubuntu0.14.04.1"
        end

        Platform:
        ---------
        x86_64-linux


             ================================================================================
             Error executing action `create` on resource 'mysql_client_installation_package[default]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             apt_package[mysql-client-5.5] (/tmp/kitchen/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb line 18) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
             ---- Begin output of apt-get -q -y install mysql-client-5.5=5.5.50-0ubuntu0.14.04.1 ----
             STDOUT: Reading package lists...
             Building dependency tree...
             Reading state information...
             STDERR: E: Version '5.5.50-0ubuntu0.14.04.1' for 'mysql-client-5.5' was not found
             ---- End output of apt-get -q -y install mysql-client-5.5=5.5.50-0ubuntu0.14.04.1 ----
             Ran apt-get -q -y install mysql-client-5.5=5.5.50-0ubuntu0.14.04.1 returned 100

             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb

       16:           mysql_client 'default' do
       17:             version new_resource.client_version
       18:             action :create
       19:           end
       20:

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:16:in `block in <class:Mysql>'

             mysql_client_installation_package("default") do
        action [:create]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :mysql_client
        cookbook_name "install_mysql"
        version "5.5.52-0ubuntu0.14.04.1"
        major_version "5.5"
        package_name "mysql-client-5.5"
        package_version "5.5.50-0ubuntu0.14.04.1"
             end

             Platform:
             ---------
             x86_64-linux


           ================================================================================
           Error executing action `install` on resource 'mysql2_chef_gem[default]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           mysql_client_installation_package[default] (/tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb line 16) had an error: Mixlib::ShellOut::ShellCommandFailed: apt_package[mysql-client-5.5] (/tmp/kitchen/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb line 18) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
           ---- Begin output of apt-get -q -y install mysql-client-5.5=5.5.50-0ubuntu0.14.04.1 ----
           STDOUT: Reading package lists...
           Building dependency tree...
           Reading state information...
           STDERR: E: Version '5.5.50-0ubuntu0.14.04.1' for 'mysql-client-5.5' was not found
           ---- End output of apt-get -q -y install mysql-client-5.5=5.5.50-0ubuntu0.14.04.1 ----
           Ran apt-get -q -y install mysql-client-5.5=5.5.50-0ubuntu0.14.04.1 returned 100

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/install_mysql/recipes/default.rb

            26:   mysql2_chef_gem 'default' do
            27:     client_version '5.5.52-0ubuntu0.14.04.1'
            28:     action :install
            29:   end
            30:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/install_mysql/recipes/default.rb:26:in `from_file'

           mysql2_chef_gem("default") do
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :mysql2_chef_gem
             cookbook_name "install_mysql"
             recipe_name "default"
             client_version "5.5.52-0ubuntu0.14.04.1"
             gem_version "0.3.17"
           end

           Platform:
           ---------
           x86_64-linux

       Recipe: rundeck::server_install
         * service[rundeck] action nothing (skipped due to action :nothing)

       Running handlers:
       [2016-09-14T15:23:28+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-09-14T15:23:28+00:00] ERROR: Exception handlers complete
       Chef Client failed. 5 resources updated in 15 seconds
       [2016-09-14T15:23:28+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-09-14T15:23:28+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-09-14T15:23:28+00:00] ERROR: mysql2_chef_gem[default] (install_mysql::default line 26) had an error: Mixlib::ShellOut::ShellCommandFailed: mysql_client_installation_package[default] (/tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb line 16) had an error: Mixlib::ShellOut::ShellCommandFailed: apt_package[mysql-client-5.5] (/tmp/kitchen/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb line 18) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
       ---- Begin output of apt-get -q -y install mysql-client-5.5=5.5.50-0ubuntu0.14.04.1 ----
       STDOUT: Reading package lists...
       Building dependency tree...
       Reading state information...
       STDERR: E: Version '5.5.50-0ubuntu0.14.04.1' for 'mysql-client-5.5' was not found
       ---- End output of apt-get -q -y install mysql-client-5.5=5.5.50-0ubuntu0.14.04.1 ----
       Ran apt-get -q -y install mysql-client-5.5=5.5.50-0ubuntu0.14.04.1 returned 100
       [2016-09-14T15:23:28+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <database-installation-ubuntu-1404>.  Please see .kitchen/logs/database-installation-ubuntu-1404.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by glennmate** [comment]
+1 on this issue. So I noticed today that my servers using the mysql cookbook, database cookbook and mysql2_chef_gem cookbook are no longer functioning with the above stack trace. Here's what I get when I attempt to manually run `apt-get install mysql-client`:

```
user@server:~$ sudo apt-get install mysql-client
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mysql-client : Depends: mysql-client-5.5 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by glennmate** [comment]
To update my last post, looks like mysql2_chef_gem is trying to push 5.5 when 5.6 is already installed. I'm not specifying any parameters with the resource, so I've updated to the below:
```
mysql2_chef_gem 'default' do
  client_version 5.6
  action :install
end
```
And will report back if this resolves the issue.

**Comment by glennmate** [comment]
Pinning the MySQL version in the `client_version` parameter has resolved my output. Chef runs are now idempotent in relation to MySQL installations. 

```
Recipe: my-cookbook::mysql
  * apt_package[libmysqlclient-dev] action install (up to date)
  * apt_package[php5-mysql] action install (up to date)
  * mysql2_chef_gem[default] action install
  Recipe: build-essential::_debian
    * apt_package[autoconf] action install (up to date)
    * apt_package[binutils-doc] action install (up to date)
    * apt_package[bison] action install (up to date)
    * apt_package[build-essential] action install (up to date)
    * apt_package[flex] action install (up to date)
    * apt_package[gettext] action install (up to date)
    * apt_package[ncurses-dev] action install (up to date)
    * mysql_client_installation_package[default] action create
      * apt_package[mysql-client-5.6] action install (up to date)
       (up to date)
    * gem_package[mysql2] action install (up to date)
     (up to date)
```

@snehitgajjar See if pinning a client_version in your resource block resolves the issue?

**Comment by snehitgajjar** [comment]
@glennmate 

It failed with what you suggested.

**Code sinppet:**

```
mysql_service 'default' do
    port '3306'
    version '5.6'
    initial_root_password rundeck_rdbms['rdbms']['dbpassword']
    run_user node['rundeck']['user']
    run_group node['rundeck']['group']
    package_version ''
    action [:create, :start]
  end

  mysql2_chef_gem 'default' do
    client_version '5.6'
    action :install
  end
```



```
================================================================================
        Error executing action `install` on resource 'apt_package[mysql-client-5.6]'
        ================================================================================

        Mixlib::ShellOut::ShellCommandFailed
        ------------------------------------
        Expected process to exit with [0], but received '100'
        ---- Begin output of apt-get -q -y install mysql-client-5.6=5.6.31-0ubuntu0.14.04.2 ----
        STDOUT: Reading package lists...
        Building dependency tree...
        Reading state information...
        STDERR: E: Version '5.6.31-0ubuntu0.14.04.2' for 'mysql-client-5.6' was not found
        ---- End output of apt-get -q -y install mysql-client-5.6=5.6.31-0ubuntu0.14.04.2 ----
        Ran apt-get -q -y install mysql-client-5.6=5.6.31-0ubuntu0.14.04.2 returned 100

        Resource Declaration:
        ---------------------
        # In /tmp/kitchen/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb

         18:       package package_name do
         19:         version package_version if package_version
         20:         options package_options if package_options
         21:         action :install
         22:       end
         23:     end

        Compiled Resource:
        ------------------
        # Declared in /tmp/kitchen/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb:18:in `block in <class:MysqlClientInstallationPackage>'

        apt_package("mysql-client-5.6") do
          package_name "mysql-client-5.6"
          action [:install]
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          declared_type :package
          cookbook_name "install_mysql"
          version "5.6.31-0ubuntu0.14.04.2"
        end

        Platform:
        ---------
        x86_64-linux


             ================================================================================
             Error executing action `create` on resource 'mysql_client_installation_package[default]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             apt_package[mysql-client-5.6] (/tmp/kitchen/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb line 18) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
             ---- Begin output of apt-get -q -y install mysql-client-5.6=5.6.31-0ubuntu0.14.04.2 ----
             STDOUT: Reading package lists...
             Building dependency tree...
             Reading state information...
             STDERR: E: Version '5.6.31-0ubuntu0.14.04.2' for 'mysql-client-5.6' was not found
             ---- End output of apt-get -q -y install mysql-client-5.6=5.6.31-0ubuntu0.14.04.2 ----
             Ran apt-get -q -y install mysql-client-5.6=5.6.31-0ubuntu0.14.04.2 returned 100

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb

       16:           mysql_client 'default' do
       17:             version new_resource.client_version
       18:             action :create
       19:           end
       20:

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:16:in `block in <class:Mysql>'

             mysql_client_installation_package("default") do
        action [:create]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :mysql_client
        cookbook_name "install_mysql"
        version "5.6"
        major_version "5.6"
        package_name "mysql-client-5.6"
        package_version "5.6.31-0ubuntu0.14.04.2"
             end

             Platform:
             ---------
             x86_64-linux


           ================================================================================
           Error executing action `install` on resource 'mysql2_chef_gem[default]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           mysql_client_installation_package[default] (/tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb line 16) had an error: Mixlib::ShellOut::ShellCommandFailed: apt_package[mysql-client-5.6] (/tmp/kitchen/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb line 18) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
           ---- Begin output of apt-get -q -y install mysql-client-5.6=5.6.31-0ubuntu0.14.04.2 ----
           STDOUT: Reading package lists...
           Building dependency tree...
           Reading state information...
           STDERR: E: Version '5.6.31-0ubuntu0.14.04.2' for 'mysql-client-5.6' was not found
           ---- End output of apt-get -q -y install mysql-client-5.6=5.6.31-0ubuntu0.14.04.2 ----
           Ran apt-get -q -y install mysql-client-5.6=5.6.31-0ubuntu0.14.04.2 returned 100

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/install_mysql/recipes/default.rb

            22:   mysql2_chef_gem 'default' do
            23:     client_version '5.6'
            24:     action :install
            25:   end
            26:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/install_mysql/recipes/default.rb:22:in `from_file'

           mysql2_chef_gem("default") do
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :mysql2_chef_gem
             cookbook_name "install_mysql"
             recipe_name "default"
             client_version "5.6"
             gem_version "0.3.17"
           end

           Platform:
           ---------
           x86_64-linux


       Running handlers:
       [2016-10-26T15:37:03+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-10-26T15:37:03+00:00] ERROR: Exception handlers complete
       Chef Client failed. 42 resources updated in 01 minutes 27 seconds
       [2016-10-26T15:37:03+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-10-26T15:37:03+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-10-26T15:37:03+00:00] ERROR: mysql2_chef_gem[default] (install_mysql::default line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: mysql_client_installation_package[default] (/tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb line 16) had an error: Mixlib::ShellOut::ShellCommandFailed: apt_package[mysql-client-5.6] (/tmp/kitchen/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb line 18) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
       ---- Begin output of apt-get -q -y install mysql-client-5.6=5.6.31-0ubuntu0.14.04.2 ----
       STDOUT: Reading package lists...
       Building dependency tree...
       Reading state information...
       STDERR: E: Version '5.6.31-0ubuntu0.14.04.2' for 'mysql-client-5.6' was not found
       ---- End output of apt-get -q -y install mysql-client-5.6=5.6.31-0ubuntu0.14.04.2 ----
       Ran apt-get -q -y install mysql-client-5.6=5.6.31-0ubuntu0.14.04.2 returned 100
       [2016-10-26T15:37:03+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <rdbms-ubuntu-1404>.  Please see .kitchen/logs/rdbms-ubuntu-1404.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by tas50** [comment]
This should all be fixed on master
